### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Sk1er** [ConorTheDev/Hypixel-Skywars-Stats#1]
Hello,
I was send this by a user on Twitter. If you would like to not have redistribution of the code please consider using a proper License. 

On another note, if you are going to use my code I request that you do not repackage it into your own (Keep in original club.sk1er base package) and to credit me.

Thank you

**Comment by ConorTheDev** [comment]
Hi. I am so sorry about that I will give you credit now. The classes were for testing and I didn't really mean to use them at the time. Updating now.
